import TEXT_STYLES from "./text-styles";
const LINE_HEIGHTS = [13, 16, 18, 19, 20, 22, 24, 25, 30, 41, 45, 68]; // px
const lineHeights = {
    0: LINE_HEIGHTS[0],
    1: LINE_HEIGHTS[1],
    2: LINE_HEIGHTS[2],
    3: LINE_HEIGHTS[3],
    4: LINE_HEIGHTS[4],
    5: LINE_HEIGHTS[5],
    6: LINE_HEIGHTS[6],
    7: LINE_HEIGHTS[7],
    8: LINE_HEIGHTS[8],
    9: LINE_HEIGHTS[9],
    10: LINE_HEIGHTS[10],
    11: LINE_HEIGHTS[11],
    [TEXT_STYLES.BODY_XS]: LINE_HEIGHTS[0],
    [TEXT_STYLES.BODY_SMALL]: LINE_HEIGHTS[1],
    [TEXT_STYLES.BODY_SMALL_EMPH]: LINE_HEIGHTS[1],
    [TEXT_STYLES.BODY_SMALL_REGULAR]: LINE_HEIGHTS[1],
    [TEXT_STYLES.BODY]: LINE_HEIGHTS[2],
    [TEXT_STYLES.BODY_REGULAR]: LINE_HEIGHTS[2],
    [TEXT_STYLES.H6]: LINE_HEIGHTS[3],
    [TEXT_STYLES.H5]: LINE_HEIGHTS[4],
    // TODO: BODY_BP_SM is deprecated and should be removed when 2.0.0 will go live
    [TEXT_STYLES.BODY_BP_SM]: LINE_HEIGHTS[4],
    [TEXT_STYLES.BODY_VIEW_S]: LINE_HEIGHTS[4],
    [TEXT_STYLES.H4]: LINE_HEIGHTS[5],
    [TEXT_STYLES.MENU_LIST_ITEM]: LINE_HEIGHTS[5],
    [TEXT_STYLES.H3]: LINE_HEIGHTS[6],
    [TEXT_STYLES.EMAIL_BODY]: LINE_HEIGHTS[7],
    [TEXT_STYLES.H2]: LINE_HEIGHTS[8],
    [TEXT_STYLES.H1]: LINE_HEIGHTS[9],
    [TEXT_STYLES.KPI]: LINE_HEIGHTS[10],
    [TEXT_STYLES.H1_ELEVATED]: LINE_HEIGHTS[11]
};
export default lineHeights;
