"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.isObject = exports.isNull = exports.isInstanceOfString = exports.isInstanceOfNumber = exports.isInstanceOfDate = exports.isInstanceOfBoolean = exports.isBoolean = exports.isArray = exports.hasUndefinedType = exports.hasStringType = exports.hasObjectType = exports.hasNumberType = exports.hasDefinedType = exports.hasBooleanType = void 0;
var has_boolean_type_1 = require("./has-boolean-type");
Object.defineProperty(exports, "hasBooleanType", { enumerable: true, get: function () { return __importDefault(has_boolean_type_1).default; } });
var has_defined_type_1 = require("./has-defined-type");
Object.defineProperty(exports, "hasDefinedType", { enumerable: true, get: function () { return __importDefault(has_defined_type_1).default; } });
var has_number_type_1 = require("./has-number-type");
Object.defineProperty(exports, "hasNumberType", { enumerable: true, get: function () { return __importDefault(has_number_type_1).default; } });
var has_object_type_1 = require("./has-object-type");
Object.defineProperty(exports, "hasObjectType", { enumerable: true, get: function () { return __importDefault(has_object_type_1).default; } });
var has_string_type_1 = require("./has-string-type");
Object.defineProperty(exports, "hasStringType", { enumerable: true, get: function () { return __importDefault(has_string_type_1).default; } });
var has_undefined_type_1 = require("./has-undefined-type");
Object.defineProperty(exports, "hasUndefinedType", { enumerable: true, get: function () { return __importDefault(has_undefined_type_1).default; } });
var is_array_1 = require("./is-array");
Object.defineProperty(exports, "isArray", { enumerable: true, get: function () { return __importDefault(is_array_1).default; } });
var is_boolean_1 = require("./is-boolean");
Object.defineProperty(exports, "isBoolean", { enumerable: true, get: function () { return __importDefault(is_boolean_1).default; } });
var is_instanceof_boolean_1 = require("./is-instanceof-boolean");
Object.defineProperty(exports, "isInstanceOfBoolean", { enumerable: true, get: function () { return __importDefault(is_instanceof_boolean_1).default; } });
var is_instanceof_date_1 = require("./is-instanceof-date");
Object.defineProperty(exports, "isInstanceOfDate", { enumerable: true, get: function () { return __importDefault(is_instanceof_date_1).default; } });
var is_instanceof_number_1 = require("./is-instanceof-number");
Object.defineProperty(exports, "isInstanceOfNumber", { enumerable: true, get: function () { return __importDefault(is_instanceof_number_1).default; } });
var is_instanceof_string_1 = require("./is-instanceof-string");
Object.defineProperty(exports, "isInstanceOfString", { enumerable: true, get: function () { return __importDefault(is_instanceof_string_1).default; } });
var is_null_1 = require("./is-null");
Object.defineProperty(exports, "isNull", { enumerable: true, get: function () { return __importDefault(is_null_1).default; } });
var is_object_1 = require("./is-object");
Object.defineProperty(exports, "isObject", { enumerable: true, get: function () { return __importDefault(is_object_1).default; } });
