"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.importEntries = exports.isTaskEntry = exports.isResolution = exports.isReference = exports.isFieldset = exports.isFieldEntry = exports.isEntry = exports.isEntries = exports.isActionableEntry = void 0;
var actionable_entry_1 = require("./actionable-entry");
Object.defineProperty(exports, "isActionableEntry", { enumerable: true, get: function () { return actionable_entry_1.isActionableEntry; } });
var entries_1 = require("./entries");
Object.defineProperty(exports, "isEntries", { enumerable: true, get: function () { return entries_1.isEntries; } });
var entry_1 = require("./entry");
Object.defineProperty(exports, "isEntry", { enumerable: true, get: function () { return entry_1.isEntry; } });
var field_entry_1 = require("./field-entry");
Object.defineProperty(exports, "isFieldEntry", { enumerable: true, get: function () { return field_entry_1.isFieldEntry; } });
var fieldset_1 = require("./fieldset");
Object.defineProperty(exports, "isFieldset", { enumerable: true, get: function () { return fieldset_1.isFieldset; } });
var reference_1 = require("./reference");
Object.defineProperty(exports, "isReference", { enumerable: true, get: function () { return reference_1.isReference; } });
var resolution_1 = require("./resolution");
Object.defineProperty(exports, "isResolution", { enumerable: true, get: function () { return resolution_1.isResolution; } });
var task_entry_1 = require("./task-entry");
Object.defineProperty(exports, "isTaskEntry", { enumerable: true, get: function () { return task_entry_1.isTaskEntry; } });
var import_entries_1 = require("./import-entries");
Object.defineProperty(exports, "importEntries", { enumerable: true, get: function () { return import_entries_1.importEntries; } });
